#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#C33332"
bspc config focused_border_color "#EEF50F"

bspc rule -a Emacs state=tiled
